splitting sfs by mutation types
popsim-consortium/analysis2 pull request #36
Opened 2022-02-09 20:45 UTC by mufernando

WIP

2022-02-10 13:44 UTC, andrewkern requested changes
I marked a few places in the PR that should be split out of the Snakefile and put into its own module

2022-02-10 13:44 UTC, andrewkern commented on benchmark/Snakefile
> +    print(dict(zip(unique, counts)))
so i think this code should be pushed to its own module in analysis, perhaps called `SFS_tools.py` and then imported to this workflow

2022-02-10 13:44 UTC, andrewkern commented on benchmark/Snakefile
> +        nonneu_fs = dadi.Spectrum(mut_afs["non_neutral"])
yep and this whole function too!

2022-02-10 16:25 UTC, petrelharp commented on benchmark/Snakefile
> +                mut_types[mid] = "neutral" if mt["is_neutral"] else "non_neutral"
```suggestion
            label = "neutral" if mt["is_neutral"] else "non_neutral"
            if mid in mut_types:
                assert mut_types[mid] == label
            else:
                mut_types[mid] = label
```

2022-02-10 16:27 UTC, petrelharp commented on benchmark/Snakefile
> +    assert sum(site_class == None) == 0
oh wait, that maybe doesn't work with numpy arrays.

2022-02-10 16:48 UTC, petrelharp commented
So - I am not actually sure what to do about the conflicts between this PR and #31???

2022-02-10 17:00 UTC, mufernando commented
Let's wait for #31 to go in, then I can apply my changes to the new file @xin-huang created. The only thing that matters in this PR is the change in the way we split the SFS by mutation class (now using the metadata).

2022-02-10 17:10 UTC, izabelcavassim commented
I will get my part of the analyses in once we get the #31 in.

2022-02-11 17:55 UTC, andrewkern commented
okay so #31 is in.  @xin-huang split these functions into a new module called `ts2fs.py` and he split the snakefile into two now. I'm not sure if we need this PR anymore @mufernando ?

2022-02-14 15:31 UTC, closed without merging