Extracting neutral-SFS only
popsim-consortium/analysis2 pull request #44
Opened 2022-02-22 15:50 UTC by izabelcavassim

To infer demographic history what we really want is the neutral-SFS.
Here I attempt to change the previous scripts a bit so we only get 
the linked effect of selection on neutral mutations, but never use the non-neutral SFS for the demo-inference analyses.
Other things that I need to work on
- [x] Get the masking approach to work both in stairwayplot and msmc
- [x] Store the non-neutral SFS somewhere and have a figure of both neutral and non-neutral SFS
- [x] Store mean and sd fitness based on the output logfile, or just plot it
- [x] Allow mask step to the msmc analyses too

2022-02-22 22:00 UTC, mufernando commented
sorry, I'm lost, but why aren't we using the same function that we have in ts2fs.py?
We could add a "stairway" option to `generate_fs()`:

https://github.com/popsim-consortium/analysis2/blob/440a21e26b9b78158904a849dbda27b7b036f72d/workflows/ts2fs.py#L55

2022-02-22 22:28 UTC, izabelcavassim commented
sure we could use that @mufernando, we just need to bootstrap the SFS for the stairwayplot differently than just outputting an sfs, if that belongs to the ts2fs.py then I don't know, it is a matter of taste and nonredundancy... I could write it there instead, but I still think that is better organized if it stay within the stairway.py script.

2022-02-22 22:38 UTC, petrelharp commented on workflows/stairway.py
> +                            neu_positions.append(m.site)
This will append a site to `neu_positions` multiple times if it has multiple neutral mutations. Is this desired?

2022-02-22 22:39 UTC, petrelharp commented on workflows/stairway.py
> +            retain = np.full(ts.get_num_mutations(), False)
The `ts.get_XXX()` methods have been depricated:
```suggestion
            retain = np.full(ts.num_mutations, False)
```

2022-02-22 22:40 UTC, petrelharp commented on workflows/stairway.py
> +                            neu_positions.append(m.site)
Ah, I see that you do `set( )` down below to get rid of the duplications. How about instead
```
                    for md in m.metadata["mutation_list"]:
                        mt.append(md["mutation_type"])
                    if set(mt) == set("neutral"):
                         neu_positions.append(m.site)
```

2022-02-26 17:12 UTC, chriscrsmith commented
Sorry for the late comment but isn't trying to extract the neutral-SFS unusual with current empirical analyses? My (maybe naive) vision was to use all/random mutations including those with selection or linked selection. Then plot a separate grey curve from a neutral simulation to represent a theoretical baseline, to quantify how much selection affects the inference.

2022-02-26 17:25 UTC, petrelharp commented
I think the idea is that in practice people often look at synonymous (~neutral) and non-synonymous changes.

2022-03-03 17:22 UTC, andrewkern commented
checking in on this PR. @izabelcavassim is this ready for a review or are you still working?

2022-03-03 21:25 UTC, izabelcavassim commented
> Member

Hi @andrewkern yeah I think you can have a look at it now, there is one conflict with the config.yaml file that I am trying to resolve, but revision is welcomed.

2022-03-15 16:51 UTC, andrewkern requested changes
a few minor comments above but note there is a run time error also:

```
TypeError in line 95 of /home/adkern/popSim/analysis2/workflows/simulation.snake:
add_dfe() got an unexpected keyword argument 'logfile'
```

in talking with @izabelcavassim about this, it seems there is a bit of code that hasn't been committed yet to this PR

2022-03-15 16:51 UTC, andrewkern commented on workflows/stairway.py
> +            mut_types = {}
change the name of `mut_types` here? many things are called "mut_type" around this bit of code

2022-03-15 16:51 UTC, andrewkern commented on workflows/stairway.py
> +                mt = []
probably want a different name rather than `mt`

2022-03-15 16:51 UTC, andrewkern commented on workflows/stairway.py
> +                for i in range(len(tmp_bool_neu)):
I think you don't have to mask neutral and non-neutral sites separately. instead use one array to keep track of the masking and another to assign neutral / non-neutral status

2022-03-16 18:02 UTC, izabelcavassim commented
@andrewkern I think it will work now, could you revise it again? Thanks

2022-07-29 23:58 UTC, andrewkern commented
darn it. i just tried to resolve the merge conflicts on this PR and messed it up. I'm going to roll it back to @izabelcavassim's commit https://github.com/popsim-consortium/analysis2/pull/44/commits/6482a7989538cc66d4c49bbcaa81746193277cbb and try to force push

2022-08-09 22:50 UTC, andrewkern commented
okay closing this PR now that #68 has been merged which incorporates many of the commits on this PR from @izabelcavassim

2022-08-09 22:50 UTC, closed without merging