Patch sp plot
popsim-consortium/analysis2 pull request #73
Opened 2022-08-10 21:34 UTC by andrewkern

here is a patch for the bug that @lntran26 found and reported in #71, which appeared to be an issue with ploting stairwayplot results. 

In examining things, what was happening was that a helper function being used to expand the list of file names with stairwayplot results to plot was expanding over too many wildcards, and so inappropriate reps (e.g. between demographies) were being plotting together.

this PR provides a fix for this bug that will close #71

2022-08-12 01:59 UTC, lntran26 requested changes
After making the additional suggested changes to the code I was able to generate stairway plots with the expected number of replicates for each of the two demographic models.

![constant_all_estimated_Ne](https://user-images.githubusercontent.com/38679445/184270408-0d25bdd5-91df-446c-bf04-50995aa14149.png)
![OOF_all_estimated_Ne](https://user-images.githubusercontent.com/38679445/184270418-d87133a3-2fe1-4299-b5bc-233093a91109.png)

2022-08-12 01:59 UTC, lntran26 commented on workflows/n_t.snake
>              seeds=seed_array,
Need to update line 186-190 to:
```
seeds=wildcards.seeds,
chrms=chrm_list,
dfes=wildcards.dfes,
demog=wildcards.demog,
annots=wildcards.annots,
```

2022-08-12 01:59 UTC, lntran26 commented on workflows/n_t.snake
>          annots=annotation_list,
Also need to change line 214 to
`annots=wildcards.annots,`

2022-08-16 07:01 UTC, andrewkern commented
thanks @lntran26 -- some of these edits didn't work for me. i've pushed further changes, fixes some other bugs that i saw, but am still trying to figure out whats going on with the SP output

2022-08-16 22:41 UTC, andrewkern commented
okay, i can now confirm that this patch is working. here are representative plots from a run of the `config.yaml` settings. Both of these are Chr21, Gamma DFE on exons:

Constant demography, 
[all_estimated_Ne.pdf](https://github.com/popsim-consortium/analysis2/files/9355071/all_estimated_Ne.pdf)

OOA:
[all_estimated_Ne (1).pdf](https://github.com/popsim-consortium/analysis2/files/9355081/all_estimated_Ne.1.pdf)

2022-08-16 22:42 UTC, andrewkern commented
i have rebased and squashed this PR so will merge.

2022-08-16 22:45 UTC, merged