Neutral simulation and N(t) analysis
popsim-consortium/analysis2 pull request #77
Opened 2022-09-08 18:40 UTC by lntran26

In this pr, I updated:
1. Version requirements for installing SLiM and snakemake (lower snakemake version can cause [error](https://github.com/snakemake/snakemake/issues/1342) when running the pipeline)
2. Arizona cluster config setting (output and error files organized more similar to Oregon cluster)
3. Snake files and config for running neutral simulation and N(t) analysis (no DFE and no annotation setting)

2022-09-13 16:42 UTC, andrewkern requested changes
so the main changes here are fine, but we want to keep the config files as they are and instead introduce a new config file to try out these changes. In addition, we might want to try out running an array of dfes that includes "none" and get that functionality to work.

One more note on this PR is the changes to importing rules from `simulation.snake` to `n_t.snake`. Ideally the `n_t.snake` workflow will make sure that trees have been simulated and if not will go and run them.

2022-09-13 16:42 UTC, andrewkern commented on workflows/config/snakemake/config.yaml
> +"dfe_list": ["none"]
```suggestion
"dfe_list": ["none", "Gamma_H17" ]
```

2022-09-13 16:42 UTC, andrewkern commented on workflows/config/snakemake/config.yaml
> +"annotation_list": ["none"]
```suggestion
"annotation_list": ["none", "ensembl_havana_104_exons"]
```

2022-09-13 16:42 UTC, andrewkern commented on workflows/config/snakemake/production-config.yml
> +"replicates": 3
should this be changed? it looks like you probably want to create a new `config` file for the no annotation runs

2022-09-13 16:42 UTC, andrewkern commented on workflows/config/snakemake/production-config.yml
> +"annotation_list": ["none"]
see comment above-- seems like rather than edit this file you should create a whole new yaml config

2022-09-13 16:42 UTC, andrewkern commented on workflows/config/snakemake/production-config.yml
> +"annotation_list": ["none"]
yeah, we don't want to have "none" in `production-config.yml` as this file will be what specifies the large run for the paper

2022-09-13 16:42 UTC, andrewkern commented on workflows/n_t.snake
> +configfile: "workflows/config/snakemake/production-config.yml"
we don't want this checked in yet-- as we develop the workflow we want to be running config.yaml or the tiny config

2022-09-13 16:42 UTC, andrewkern commented on workflows/n_t.snake
> +#     rules.simulation_all.input,
should this be `rules.simulation_all.output`?

2022-09-13 16:42 UTC, andrewkern commented on workflows/n_t.snake
> +# use rule * from simulation_workflow as simulation_*
we want this in to be able to check easily enough if simulations are complete

2022-09-13 16:42 UTC, andrewkern commented on workflows/n_t.snake
> +    threads: 30
going to get machines with 30 cores on most clusters

2022-09-13 16:42 UTC, andrewkern commented on workflows/simulation.snake
> +configfile: "workflows/config/snakemake/production-config.yml"
we don't want this here yet

2022-09-20 02:06 UTC, lntran26 commented
@andrewkern I made the requested changes for this PR based on your feedback. It's ready for review again.

2022-09-20 13:28 UTC, andrewkern approved these changes
I went through the code and it looks good, and last night I was able to run the `simulation.snake` and `n_t.snake` workflows using the new `neutral-config.yml` file. Seems all set to me @lntran26! 

I'm going to merge this PR.

2022-09-20 13:28 UTC, merged